[package]
name = "find-process"
version = "0.0.1"
authors = ["ck"]
license = "ISC"
edition = "2018"
exclude = ["find-process.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30.5"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]