[package]
name = "tsprocess-rust"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["NativeMemoryReader.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neon = { version = "1", features = ["sys"] }
cfg-if = "1.0.0"
paste = "1.0.15"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.57.0", features = [
    "Win32_Foundation",
    "Win32_System_Kernel",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_ProcessStatus",
    "Wdk_System",
    "Wdk_System_Threading"
] }
