name: Build and Deploy

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

flow-prepare-jobs: &flow-prepare-jobs
  - name: Checkout 🛎️
    uses: actions/checkout@v3

  - name: Install Node.js 🔧
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: Install Rust 🔧
    uses: ATiltedTree/setup-rust@v1
    with:
      rust-version: stable
      components: clippy

  - name: Install Deps 🔧
    run: |
      npm install -g pnpm@^8
      pnpm install --frozen-lockfile

jobs:
  lint:
    runs-on: "windows-latest"
    name: "Lint project"
    steps:
      <<: *flow-prepare-jobs

      - name: Lint project
      run: |
        pnpm run prettier:ci

  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]

    runs-on: "${{ matrix.os }}"
    name: "Build on ${{ matrix.os }}"
    steps:
      <<: *flow-prepare-jobs

      - name: Build App 🔧
        run: |
          pnpm run build

      # - name: Upload Artifact (Linux)
      #   if: startsWith( matrix.os, 'ubuntu' )
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-${{ github.ref_name }}
      #     path: dist/tosu
  
      # - name: Upload Artifact (Mac OS)
      #   if: startsWith( matrix.os, 'macos' )
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-${{ github.ref_name }}
      #     path: dist/tosu.app

      - name: Upload Artifact (Windows)
        if: startsWith( matrix.os, 'windows' )
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: packages/tosu/dist/tosu.exe
