name: Build and Deploy

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]

    runs-on: "${{ matrix.os }}"
    name: "Build on ${{ matrix.os }}"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set output pr sha
        if: github.event_name == 'pull_request'
        id: set-pr-sha
        shell: bash
        run: |
          echo "SHORT_PR_SHA=$(git rev-parse HEAD | cut -c 1-8)" >> "$GITHUB_OUTPUT"

      - name: Install Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust 🔧
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install Deps 🔧
        run: |
          npm install -g pnpm@^8
          pnpm install --frozen-lockfile

      - name: Build App 🔧
        run: |
          pnpm run build

      # - name: Upload Artifact (Linux)
      #   if: startsWith( matrix.os, 'ubuntu' )
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-${{ github.ref_name }}
      #     path: dist/tosu
  
      # - name: Upload Artifact (Mac OS)
      #   if: startsWith( matrix.os, 'macos' )
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-${{ github.ref_name }}
      #     path: dist/tosu.app

      - name: Upload Artifact (Windows)
        if: startsWith( matrix.os, 'windows' )
        uses: actions/upload-artifact@v3
        with:
          name: tosu-${{ matrix.os }}-${{ steps.set-pr-sha.outputs.SHORT_PR_SHA || github.ref_name }}
          path: packages/tosu/dist/tosu.exe
